#!/bin/bash
###  Install the Apache with PHP  ### 
#(detailed instructions can be found at http://www.instructables.com/id/Raspberry-Pi-Web-Server/step7/Install-Apache-with-PHP/)

sudo apt-get update # updates the repository locations
sudo apt-get install apache2 php5 libapache2-mod-php5 # install apache & php
sudo groupadd www-data
sudo usermod -g www-data www-data
sudo service apache2 restart
sudo chown -R pi /var/www

###  Install the MySQL and  ###
sudo apt-get install mysql-server mysql-client php5-mysql

###  Give the web server access to the i2c bus  ###
